package openresty

import (
	"fmt"
	"net/url"
	"strings"
)

func RenderRouteConfig(routes []Route, cfg ConfigSnapshot, options RenderOptions) (string, []SupportFile, error) {
	var builder strings.Builder
	builder.WriteString("# This file is generated by DuShengCDN. Do not edit manually.\n")
	supportFiles := make([]SupportFile, 0)
	for _, route := range routes {
		domains := route.Domains
		if len(domains) == 0 && strings.TrimSpace(route.Domain) != "" {
			domains = []string{route.Domain}
		}
		if len(domains) == 0 {
			return "", nil, fmt.Errorf("route %s domains are invalid", route.Domain)
		}
		serverNames := renderServerNames(domains)
		displayName := route.SiteName
		if strings.TrimSpace(displayName) == "" {
			displayName = domains[0]
		}
		cacheConfig := routeCacheConfig{
			Enabled: route.CacheEnabled,
			Policy:  route.CachePolicy,
			Rules:   route.CacheRules,
		}
		limitConfig := routeLimitConfig{
			LimitConnPerServer: route.LimitConnPerServer,
			LimitConnPerIP:     route.LimitConnPerIP,
			LimitRate:          route.LimitRate,
		}
		proxyBufferingConfig := routeProxyBufferingConfig{
			Mode: normalizeProxyBufferingMode(route.ProxyBufferingMode),
		}
		regionConfig := routeRegionRestrictionConfig{
			Enabled:   route.RegionRestrictionEnabled && len(route.RegionRestrictionCountries) > 0,
			Mode:      normalizeRegionMode(route.RegionRestrictionMode),
			Countries: route.RegionRestrictionCountries,
		}
		wafConfig := routeWAFConfig{
			Enabled: route.WAFEnabled,
			Mode:    normalizeWAFMode(route.WAFMode),
		}
		ccConfig := routeCCConfig{
			Enabled: route.CCEnabled,
			Mode:    normalizeCCMode(route.CCMode),
		}
		powRequired := route.PoWEnabled || (ccConfig.Enabled && ccConfig.Mode == CCModePoW)
		upstreamConfig, err := buildRouteUpstreamConfig(route, route.Upstreams, options)
		if err != nil {
			return "", nil, fmt.Errorf("璺敱 %s 婧愮珯瑙ｆ瀽涓嶅畨鍏? %w", route.Domain, err)
		}
		if upstreamConfig.UsesNamedUpstream {
			builder.WriteString(renderNamedUpstreamBlock(upstreamConfig))
		}
		if !route.EnableHTTPS {
			builder.WriteString(renderHTTPProxyServer(serverNames, route.OriginURL, route.OriginHost, route.CustomHeaders, cacheConfig, limitConfig, proxyBufferingConfig, regionConfig, wafConfig, ccConfig, upstreamConfig, powRequired, route.BasicAuthEnabled, route.BasicAuthUsername, route.BasicAuthPasswordHash, cfg))
			continue
		}
		if route.CertID == nil || *route.CertID == 0 {
			return "", nil, fmt.Errorf("璺敱 %s 鏈厤缃瘉涔?", route.Domain)
		}
		if len(route.CertIDs) == 0 {
			return "", nil, fmt.Errorf("璺敱 %s 鏈厤缃瘉涔?", route.Domain)
		}
		certificateByID := make(map[uint]TLSCertificate, len(route.Certificates))
		for _, certificate := range route.Certificates {
			if certificate.ID == 0 {
				continue
			}
			certificateByID[certificate.ID] = certificate
			supportFiles = append(supportFiles,
				SupportFile{Path: CertFileName(certificate.ID), Content: NormalizePEM(certificate.CertPEM)},
				SupportFile{Path: KeyFileName(certificate.ID), Content: NormalizePEM(certificate.KeyPEM)},
			)
		}

		httpOnlyDomains := make([]string, 0, len(domains))
		domainsByCertID := make(map[uint][]string, len(route.CertIDs))
		for index, domain := range domains {
			if index >= len(route.DomainCertIDs) || route.DomainCertIDs[index] == 0 {
				httpOnlyDomains = append(httpOnlyDomains, domain)
				continue
			}
			domainsByCertID[route.DomainCertIDs[index]] = append(
				domainsByCertID[route.DomainCertIDs[index]],
				domain,
			)
		}
		for _, certID := range route.CertIDs {
			assignedDomains := domainsByCertID[certID]
			if len(assignedDomains) == 0 {
				continue
			}
			certificate, ok := certificateByID[certID]
			if !ok {
				return "", nil, fmt.Errorf("route %s certificate %d does not exist", route.Domain, certID)
			}
			if err := validateCertificateCoverage(certificate, assignedDomains); err != nil {
				return "", nil, fmt.Errorf("site %s certificate validation failed: %w", displayName, err)
			}
		}

		if route.RedirectHTTP {
			if len(httpOnlyDomains) > 0 {
				builder.WriteString(renderHTTPProxyServer(renderServerNames(httpOnlyDomains), route.OriginURL, route.OriginHost, route.CustomHeaders, cacheConfig, limitConfig, proxyBufferingConfig, regionConfig, wafConfig, ccConfig, upstreamConfig, powRequired, route.BasicAuthEnabled, route.BasicAuthUsername, route.BasicAuthPasswordHash, cfg))
			}
			for _, certID := range route.CertIDs {
				assignedDomains := domainsByCertID[certID]
				if len(assignedDomains) == 0 {
					continue
				}
				builder.WriteString(renderHTTPRedirectServer(renderServerNames(assignedDomains), regionConfig, wafConfig, ccConfig))
			}
		} else {
			builder.WriteString(renderHTTPProxyServer(serverNames, route.OriginURL, route.OriginHost, route.CustomHeaders, cacheConfig, limitConfig, proxyBufferingConfig, regionConfig, wafConfig, ccConfig, upstreamConfig, powRequired, route.BasicAuthEnabled, route.BasicAuthUsername, route.BasicAuthPasswordHash, cfg))
		}
		for _, certID := range route.CertIDs {
			assignedDomains := domainsByCertID[certID]
			if len(assignedDomains) == 0 {
				continue
			}
			builder.WriteString(renderHTTPSServer(renderServerNames(assignedDomains), route.OriginURL, route.OriginHost, certID, route.CustomHeaders, cacheConfig, limitConfig, proxyBufferingConfig, regionConfig, wafConfig, ccConfig, upstreamConfig, powRequired, route.BasicAuthEnabled, route.BasicAuthUsername, route.BasicAuthPasswordHash, cfg))
		}
	}
	return builder.String(), DedupeSupportFiles(supportFiles), nil
}

func renderHTTPProxyServer(serverNames string, originURL string, originHost string, customHeaders []CustomHeader, cacheConfig routeCacheConfig, limitConfig routeLimitConfig, proxyBufferingConfig routeProxyBufferingConfig, regionConfig routeRegionRestrictionConfig, wafConfig routeWAFConfig, ccConfig routeCCConfig, upstreamConfig routeUpstreamConfig, powEnabled bool, basicAuthEnabled bool, basicAuthUsername string, basicAuthPasswordHash string, cfg ConfigSnapshot) string {
	return fmt.Sprintf("server {\n    listen 80;\n    server_name %s;\n    set $dushengcdn_request_reason \"\";\n%s%s    location / {\n%s%s%s%s%s%s    }\n%s}\n\n", serverNames, renderRouteAccessBlock(powEnabled, regionConfig, wafConfig, ccConfig), renderPowLocationBlocks(powEnabled), renderBasicAuthBlock(basicAuthEnabled, basicAuthUsername, basicAuthPasswordHash), renderProxyHeaderBlock(originURL, originHost, customHeaders, upstreamConfig, cfg), renderRouteProxyBufferingBlock(proxyBufferingConfig), renderRouteLimitBlock(limitConfig), renderRouteCacheBlock(cacheConfig, cfg), renderProxyPassBlock(originURL, upstreamConfig), renderPowStaticLocationBlock(powEnabled))
}

func renderHTTPRedirectServer(serverNames string, regionConfig routeRegionRestrictionConfig, wafConfig routeWAFConfig, ccConfig routeCCConfig) string {
	return fmt.Sprintf("server {\n    listen 80;\n    server_name %s;\n    set $dushengcdn_request_reason \"\";\n%s\n    return 301 https://$host$request_uri;\n}\n\n", serverNames, renderRegionRestrictionBlock(regionConfig, wafConfig, ccConfig))
}

func renderHTTPSServer(serverNames string, originURL string, originHost string, certificateID uint, customHeaders []CustomHeader, cacheConfig routeCacheConfig, limitConfig routeLimitConfig, proxyBufferingConfig routeProxyBufferingConfig, regionConfig routeRegionRestrictionConfig, wafConfig routeWAFConfig, ccConfig routeCCConfig, upstreamConfig routeUpstreamConfig, powEnabled bool, basicAuthEnabled bool, basicAuthUsername string, basicAuthPasswordHash string, cfg ConfigSnapshot) string {
	certPath := fmt.Sprintf("%s/%s", CertDirPlaceholder, CertFileName(certificateID))
	keyPath := fmt.Sprintf("%s/%s", CertDirPlaceholder, KeyFileName(certificateID))
	return fmt.Sprintf("server {\n    listen 443 ssl;\n    http2 on;\n    server_name %s;\n    ssl_certificate %s;\n    ssl_certificate_key %s;\n    set $dushengcdn_request_reason \"\";\n%s%s    location / {\n%s%s%s%s%s%s    }\n%s}\n\n", serverNames, certPath, keyPath, renderRouteAccessBlock(powEnabled, regionConfig, wafConfig, ccConfig), renderPowLocationBlocks(powEnabled), renderBasicAuthBlock(basicAuthEnabled, basicAuthUsername, basicAuthPasswordHash), renderProxyHeaderBlock(originURL, originHost, customHeaders, upstreamConfig, cfg), renderRouteProxyBufferingBlock(proxyBufferingConfig), renderRouteLimitBlock(limitConfig), renderRouteCacheBlock(cacheConfig, cfg), renderProxyPassBlock(originURL, upstreamConfig), renderPowStaticLocationBlock(powEnabled))
}

func renderServerNames(domains []string) string {
	return strings.Join(domains, " ")
}

func renderProxyHeaderBlock(originURL string, originHost string, customHeaders []CustomHeader, upstreamConfig routeUpstreamConfig, cfg ConfigSnapshot) string {
	var builder strings.Builder
	if strings.TrimSpace(originHost) != "" {
		builder.WriteString(fmt.Sprintf("        proxy_set_header Host %s;\n", QuoteNginxHeaderValue(originHost)))
	} else {
		builder.WriteString("        proxy_set_header Host $host;\n")
	}
	if upstreamServerName := resolveUpstreamServerName(originURL, originHost); upstreamServerName != "" {
		builder.WriteString("        proxy_ssl_server_name on;\n")
		builder.WriteString(fmt.Sprintf("        proxy_ssl_name %s;\n", QuoteNginxHeaderValue(upstreamServerName)))
		builder.WriteString("        proxy_ssl_verify on;\n")
		builder.WriteString("        proxy_ssl_verify_depth 3;\n")
		builder.WriteString("        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;\n")
	}
	builder.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	builder.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	builder.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	builder.WriteString("        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;\n")
	builder.WriteString("        proxy_next_upstream_tries 3;\n")
	builder.WriteString("        proxy_next_upstream_timeout 10s;\n")
	if cfg.WebsocketEnabled {
		builder.WriteString("        proxy_http_version 1.1;\n")
		builder.WriteString("        proxy_set_header Connection $connection_upgrade;\n")
		builder.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
	} else if upstreamConfig.UsesNamedUpstream {
		builder.WriteString("        proxy_http_version 1.1;\n")
		builder.WriteString("        proxy_set_header Connection \"\";\n")
	}
	for _, header := range customHeaders {
		builder.WriteString(fmt.Sprintf("        proxy_set_header %s %s;\n", header.Key, QuoteNginxHeaderValue(header.Value)))
	}
	return builder.String()
}

func renderRouteProxyBufferingBlock(config routeProxyBufferingConfig) string {
	if normalizeProxyBufferingMode(config.Mode) != ProxyBufferingModeOff {
		return ""
	}
	return "        proxy_buffering off;\n        proxy_request_buffering off;\n        proxy_max_temp_file_size 0;\n"
}

func renderRouteLimitBlock(limitConfig routeLimitConfig) string {
	if limitConfig.LimitConnPerServer <= 0 && limitConfig.LimitConnPerIP <= 0 && strings.TrimSpace(limitConfig.LimitRate) == "" {
		return ""
	}
	var builder strings.Builder
	if limitConfig.LimitConnPerServer > 0 {
		builder.WriteString(fmt.Sprintf("        limit_conn dushengcdn_conn_per_server %d;\n", limitConfig.LimitConnPerServer))
	}
	if limitConfig.LimitConnPerIP > 0 {
		builder.WriteString(fmt.Sprintf("        limit_conn dushengcdn_conn_per_ip %d;\n", limitConfig.LimitConnPerIP))
	}
	if strings.TrimSpace(limitConfig.LimitRate) != "" {
		builder.WriteString(fmt.Sprintf("        limit_rate %s;\n", limitConfig.LimitRate))
	}
	return builder.String()
}

func renderProxyPassBlock(originURL string, upstreamConfig routeUpstreamConfig) string {
	parsed, err := url.Parse(originURL)
	if err != nil || parsed.Host == "" || parsed.Scheme == "" {
		return fmt.Sprintf("        proxy_pass %s;\n", originURL)
	}
	if upstreamConfig.UsesNamedUpstream {
		return fmt.Sprintf("        proxy_pass %s://%s%s;\n", upstreamConfig.Scheme, upstreamConfig.Name, upstreamConfig.ProxyPassURI)
	}
	return fmt.Sprintf("        proxy_pass %s;\n", originURL)
}
